apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm_python_helloworld/manifests
    repoURL: https://github.com/seetdev-udacity/nd064_argocd_demo.git
    targetRevision: HEAD
  syncPolicy: {}