apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-ngnix-alphine
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm_ngnix_alphine/manifests
    repoURL: https://github.com/seetdev-udacity/nd064_argocd_demo.git
    targetRevision: HEAD
  syncPolicy: {}